services:
  - type: web
    name: bhoomisetu-agri-ai
    env: python
    pythonVersion: "3.10"
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.web.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATA_GOV_API_KEY
        sync: false
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
      - key: DEBUG
        value: "False"
